### ISSUE TITLE
log.debug uses console.log

### ISSUE THREAD

**Issue by RazerM** [shellscape/loglevelnext#12]
* Node Version: 10.13.0
* NPM Version: 6.10.3
* loglevelnext Version: 3.0.1

### Expected Behavior

`log.debug` uses `console.debug`.

### Actual Behavior

`log.debug` uses `console.log`

### How can we reproduce the behavior?

Use `log.debug` but disable debug in the browser console. The messages will remain.

---

The debug method is hardcoded to do this:

https://github.com/shellscape/loglevelnext/blob/cc35e2878fc82a1c3dcde7ef6ac16e2e15164873/lib/factory/MethodFactory.js#L95-L98

Could this be made optional or removed completely? I configure loglevel to be silent in production, but it's nice in development to be able to use the browser's log level toggles to enable/disable debug messages.

**Comment by shellscape** [comment]
That was put in place due to Node v6 not having the method https://nodejs.org/docs/latest-v6.x/api/console.html, and at the time of writing it was missing in a few of the browsers as well. 

Things have changed a bit since then, and I'd be happy to accept a change to properly check if the method exists before reassigning it.
