### ISSUE TITLE
Don't use eval, as it breaks with CSP (in chrome extensions etc)

### ISSUE THREAD

**Issue by kurtextrem** [shellscape/loglevelnext#2]
* Operating System: Win10 x64
* Node Version: v10 (Canary)
* Browser and Version (if applicable):
* NPM Version: latest
* loglevelnext Version: 1.0.3

- [x] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Expected Behavior

In `dist`, there is no `eval()` used

### Actual Behavior

`eval(...)` is used 3 times.

`loglevelnext.js:103 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' http://localhost:8080".`

### For Bugs; How can we reproduce the behavior?

Get a Chrome extension running, load loglevelnext (only the non-minified)

**Comment by shellscape** [comment]
It would seem the source code disagrees. https://github.com/shellscape/loglevelnext/search?utf8=%E2%9C%93&q=eval&type=

The `eval` calls you're actually referencing are part of the browser bundle, which is created by webpack. We don't have any control over how webpack puts that together, so your issue is better taken up with that project.

**Comment by shellscape** [comment]
I blame my long day today for not spotting this off the bat: `dist/loglevelnext.js` is the development bundle. `dist/loglevelnext.min.js`  is the production bundle. You'll have to use `loglevelnext.min.js` if you want to get around CSP on Chrome. 🍻

**Comment by jjeising** [comment]
@shellscape I would like to reopen this issue.

Together with webpack-contrib/webpack-hot-client#17 this essential says: you can't use `webpack-hot-client` together with a sane CSP. This is a bit strange, as the only use of `eval()` in my current configuration is within this include of `loglevelnext`.

I understand you don't want to change `webpack-hot-client` to the minimised version, but is there any reason to use `eval()` in the development build of `loglevennext`? Another option might be to not use a dist version in `webpack-hot-client`?

As you are in control of everything here, it should be possible to find a solution for this, shouldn't it?

**Comment by shellscape** [comment]
@jjeising it looks like your reply is more about webpack-hot-client than loglevelnext, so this probably isn't the best place for the reply.

> this essential says: you can't use webpack-hot-client together with a sane CSP

I'd say that moreso says that if you want to use the module in a niche environment that you'll have to implement the proper workaround. the issue you linked to there has several possible workarounds I'd encourage you to try. the extension worked quiet well for me during tests. it's unfortunate, but a CSP environment is rather unique, and definitely not in the majority. a workaround or extension to work with CSP more easily on your end is preferable to modifying a rather standard setup.
`loglevelnext` uses webpack to build the bundles, and webpack uses `eval` in development mode. when folks are working in a development environment they expect a development script, which is why that bundle exists in two versions.

I can't justify monkeypatching a development module to use a production script for a niche usergroup, especially when there are lots of workarounds available for that niche.

**Comment by jjeising** [comment]
> it looks like your reply is more about webpack-hot-client than loglevelnext, so this probably isn't the best place for the reply.

I'm sorry, this is probably more of a meta issue. I thought about both projects, but it depends were you would like to fix this. In the end I was with you in the reasoning to not change the include in `webpack-hot-client`, so this issue looked more reasonable.

> the issue you linked to there has several possible workarounds I'd encourage you to try.

And I can think of some more. I can modify my application not to send headers in development mode, and so on… but why do this, when there is one little dependency that does not conform to the local webpack config.
Using CSP in development can show problems early, without separate testing under production conditions.

> when folks are working in a development environment they expect a development script, which is why that bundle exists in two versions.

That's totally fine, and…

> I can't justify monkeypatching a development module to use a production script for a niche usergroup, 

Thats not what I asked for. But there are two options:

> loglevelnext uses webpack to build the bundles, and webpack uses eval in development mode. 

**Option 1**: Is there a reason not to configure webpack to not use eval here?

Without eval in the development version here there would be no problem.

**Option 2**: Why does `webpack-hot-client` need to include a pre build version when all dependencies run through webpack nontheless?

Without the prebuild version my local webpack config with a different than standard `devtool` configuration there would be no problem.

**Comment by shellscape** [comment]
> Option 2: Why does webpack-hot-client need to include a pre build version when all dependencies run through webpack nontheless?

It's being treated as a complete client-side library. That's intentional. Minimizes the possibility for conflicts and unforeseen errors.

> Option 1: Is there a reason not to configure webpack to not use eval here?

That much I can't answer. webpack@4 has two distinct modes, and I let the default settings do their thing there. I'd recommend asking about that in [webpack](/webpack/webpack/issues) and linking back to here. There may be side-effects to doing so, if an option even exists to not use `eval` in development builds. I'm not even aware if there are CSP-specific settings in webpack - I've never worked in that environment. If webpack supports a development build with CSP considerations, that's something we can look at.

**Comment by jjeising** [comment]
> I'm not even aware if there are CSP-specific settings in webpack - I've never worked in that environment. If webpack supports a development build with CSP considerations, that's something we can look at.

There is no _make everything fine for CSP_ option, but this is directly related to the `devtool` option. But it is not too complicated.

The default option for `development` mode [is `eval`](https://github.com/webpack/webpack/blob/fde018300aa52262c384e937c408d5dd97d62951/lib/WebpackOptionsDefaulter.js#L25). This leads to the mentioned problems here. [The documentation](https://webpack.js.org/configuration/devtool/) explains all modes, their up- and downsides and makes recommendations.

The main argument for using `eval` based source-maps is build speed. As we talk about the dist development version of this package, and this module is a few hundered lines I would recommend the  `inline-source-map` option. It's slower, but provides a very similar output format and full source maps.
If you don't need source maps in the dist version setting `devtool` to `false` is also fine.

I've submitted [a pull request](https://github.com/shellscape/loglevelnext/pull/3) with the mentioned option.

**Comment by shellscape** [comment]
👍 to doing the leg work. Please allow me some time to get up to speed. I'm presently trying to get webpack companion modules updated for v4, and it's a mess.
